### ISSUE TITLE
proposal: allow fine grained rules for distinct kinds of resources 

### ISSUE THREAD

**Issue by cristianvasquez** [zazukoians/trifid-handler-sparql#15]
trifid-handler-sparql makes a difference between resources and containers, having an implicit container logic, which is 'if ends with a slash'

Currently, it's configured in the following way:

```yaml
middlewares:
  # […]
  sparql-handler:
    module: trifid-handler-sparql
    config:
      endpointUrl: https://dbpedia.org/sparql
      resourceExistsQuery: "ASK { <${iri}> ?p ?o }"
      resourceGraphQuery: "DESCRIBE <${iri}>"
      containerExistsQuery: "ASK { ?s a ?o. FILTER REGEX(STR(?s), \"^${iri}\") }"
      containerGraphQuery: "CONSTRUCT { ?s a ?o. } WHERE { ?s a ?o. FILTER REGEX(STR(?s), \"^${iri}\") }"
```

I think it would be more flexible if one could accept patterns to handle all sorts of resources using Regexp (or something simpler), in the following way:

```
middlewares:
  # […]
  sparql-handler:
    module: trifid-handler-sparql
    config:
	endpointUrl: https://dbpedia.org/sparql
	queries: 
		container:
			match: /\/$/
			existsQuery: "ASK { ?s a ?o. FILTER REGEX(STR(?s), \"^${iri}\") }"
			graphQuery: "CONSTRUCT { ?s a ?o. } WHERE { ?s a ?o. FILTER REGEX(STR(?s), \"^${iri}\") }"
		resource:			  
			existsQuery: "ASK { <${iri}> ?p ?o }"
			graphQuery: "DESCRIBE <${iri}>"
```
Where resource (the last definition) acts as a fall-back.

This would allow defining of fine-grained rules for different kinds of entities.

Examples:

- .well-known
- Metadata in a specific named graph.
- Add limits to especially large entities.

Additionally, one could define other patterns for containers.
